### ISSUE TITLE
ABD Work by 30 Oct

### ISSUE THREAD

**Issue by aaqansar** [aaqansar/NUnitExampleProject#4]
**Selenium**

1. Open FB
2. Enter wrong password
3. Fetch error message

**String Function C#**

4. count character length of error message
5. count how many time a exist in string

**Comment by abkhan1006** [comment]
@aaqansar Completed the task and moved to the "**Abd_facebook**" branch. Please confirm.

Thanks for your help!

**Comment by aaqansar** [comment]
@abkhan1006 - I have reviewed the code and has 3 points which need to be rectified.

1. Line #44 ,No use of this code, unnecessary written kindly remove and memory is initialized to its object.
![image](https://user-images.githubusercontent.com/33342119/198967900-fa94468d-8d2f-48ec-a9a8-aaf0bd4f7d9c.png)

2. Line #48, has space in character, please remove it unless it give console error and build get failed.
![image](https://user-images.githubusercontent.com/33342119/198968199-09ddd13d-f69c-4ebd-a457-eb52726a3f53.png)

3. Please add Teardown code, provide proper naming convention to variable and method.

I would expect and early push, this time create a pull request , tagged to this issue ID.

**Comment by abkhan1006** [comment]
@aaqansar Point1 and Point is completed and pushed. Please confirm.

**Comment by aaqansar** [comment]
@abkhan1006 Pull request merge and now code is available in master.
